### ISSUE TITLE
error in google chrome

### ISSUE THREAD

**Issue by 0ktavandi** [benso-io/posta#6]
<img width="1274" alt="Screen Shot 2021-03-13 at 10 50 23" src="https://user-images.githubusercontent.com/26356781/111018236-49486800-83ea-11eb-988b-ceeacf9aea4a.png">

**Comment by payloadartist** [comment]
Still facing this issue.

**Comment by chensos** [comment]
Thanks for reporting! 
I think i know why. I pushed another fix, can you please check?

Additionally can you please describe the scenario that results in such error?

**Comment by naglienso** [comment]
> Still facing this issue.

We are looking into this and will push a fix soon, meanwhile you can use it through the node package based on chromium.
